# ============================================================================
# ArgoCD Application - Production Environment
# Deploys InfraScore to prod namespace using Multiple Sources
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrascore-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    # מקור 1: ה-Umbrella Chart שיצרת בתיקיית helm
    - repoURL: https://github.com/DrLemesh/InfraScore
      targetRevision: main
      path: helm # הנתיב המעודכן שבו נמצא ה-Chart.yaml הראשי
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
    
    # מקור 2: ריפו הגיטאופס שבו נמצאים ה-Values
    - repoURL: https://github.com/DrLemesh/infrascore-gitops
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=false
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m